### ISSUE TITLE
 "error: the following snap files do not contain PM session"

### ISSUE THREAD

**Issue by hjack123** [r3fang/SnapATAC#101]
what could be the reason that I have finished  snaptools snap-add-pmat
but x.sp = addPmatToSnap(x.sp); still says snap file dosent contain PM session?

**Comment by r3fang** [comment]
What is the error message?

**Comment by hjack123** [comment]
snaptools snap-add-pmat --snap-file A549.snap --peak-file ../snapATAC/snap.atac.peaks.combined.bed
 




Traceback (most recent call last):
  File "/home/data/apps/anaconda3/envs/py27/bin/snaptools", line 38, in <module>
    parse_args()    
  File "/home/data/apps/anaconda3/envs/py27/lib/python2.7/site-packages/snaptools/parser.py", line 176, in parse_args
    verbose=args.verbose)
  File "/home/data/apps/anaconda3/envs/py27/lib/python2.7/site-packages/snaptools/add_pmat.py", line 170, in snap_pmat
    f = h5py.File(snap_file, "a", libver='earliest');
  File "/home/data/apps/anaconda3/envs/py27/lib/python2.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/home/data/apps/anaconda3/envs/py27/lib/python2.7/site-packages/h5py/_hl/files.py", line 184, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 105, in h5py.h5f.create
IOError: Unable to create file (unable to open file: name = 'A549.snap', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)

**Comment by r3fang** [comment]
Can you use snap-del to remove pmat? And addd it again?

**Comment by hjack123** [comment]
Hi when I did that it says

snaptools snap-del --snap-file A549.snap --session-name PM

error: --session-name PM does not exist in A549.snap
