### ISSUE TITLE
Error in generating a Snap file from a Bed file - IndexError: list index out of range

### ISSUE THREAD

**Issue by joepelt** [r3fang/SnapATAC#208]
Hi, I am trying to generate a Snap file from a Bed file. 

Here is the code I enter:

snaptools snap-pre  \
	--input-file=peaks.bed  \
	--output-snap=demo.snap  \
	--genome-name=mm10  \
	--genome-size=mm10.chrom.sizes  \
	--min-mapq=30  \
	--min-flen=0  \
	--max-flen=1000  \
	--keep-chrm=TRUE  \
	--keep-single=TRUE  \
	--keep-secondary=False  \
	--overwrite=True  \
	--min-cov=100  \
	--verbose=True

After I enter the code, the following output appears:

Traceback (most recent call last):
  File "/gpfs/commons/home/jpelt/.local/share/r-miniconda/envs/r-reticulate/bin/snaptools", line 38, in <module>
    parse_args()
  File "/gpfs/commons/home/jpelt/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/snaptools/parser.py", line 144, in parse_args
    verbose=args.verbose)
  File "/gpfs/commons/home/jpelt/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/snaptools/snap_pre.py", line 206, in snap_pre
    if not snaptools.utilities.isQuerynameSorted(input_file, file_format):
  File "/gpfs/commons/home/jpelt/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/snaptools/utilities.py", line 118, in isQuerynameSorted
    return(isBedQuerynameSorted(fname))
  File "/gpfs/commons/home/jpelt/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/snaptools/utilities.py", line 166, in isBedQuerynameSorted
    cur_barcode = str(item).split()[3];
IndexError: list index out of range

Does anyone have any idea of why my list index is out of range? Apologies in advance if this is very basic - I am a bit new to SnapATAC.

**Comment by wenhuihuang1979** [comment]
root@b02779cbbc78:/home/ec2-user/CD19_CAR_CD8Tcells/outs# snaptools snap-pre --input-f^C-output-snap=possorted_bam.snap.nsrt.snap --genome-name=hg38 --genome-size=/home/ec2-user/hg38.chrom.sizes --min-mapq=30 --min-flen=0 --max-flen=1000 --keep-chrm=TRUE --keep-single=TRUE --keep-secondary=False --overwrite=True --max-num=100000 --min-cov=100 --verbose=True       root@b02779cbbc78:/home/ec2-user/CD19_CAR_CD8Tcells/outs# snaptools snap-pre --input-file=atat_CD19_CAR_CD8Tcells_fragments.srt.bed.gz --output-snap=possorted_bam.snap.nsrt.snap --genome-name=hg38 --genome-size=/home/ec2-user/hg38.chrom.sizes --min-mapq=30 --min-flen=0 --max-flen=1000 --keep-chrm=TRUE --keep-single=TRUE --keep-secondary=False --overwrite=True --max-num=100000 --min-cov=100 --verbose=True
Traceback (most recent call last):
  File "/usr/local/bin/snaptools", line 38, in <module>
    parse_args()
  File "/usr/local/lib/python2.7/dist-packages/snaptools/parser.py", line 144, in parse_args

    verbose=args.verbose)
  File "/usr/local/lib/python2.7/dist-packages/snaptools/snap_pre.py", line 224, in snap_pre
    barcode_dict = snaptools.snap.getBarcodesFromInput(input_file, file_format);
  File "/usr/local/lib/python2.7/dist-packages/snaptools/snap.py", line 177, in getBarcodesFromInput
    return getBarcodesFromBed(fname);
  File "/usr/local/lib/python2.7/dist-packages/snaptools/snap.py", line 256, in getBarcodesFromBed
    barcode = _read.split()[3].split(":")[0].upper();
IndexError: list index out of range

same here
