### ISSUE TITLE
.thanks...

### ISSUE THREAD

**Issue by hjack123** [r3fang/SnapATAC#80]
snaptools snap-add-bmat --snap-file=atac_pbmc_5k_nextgem.snap --bin-size-lis 5000 --verbose=True
===== reading the barcodes and bins ======
@AM	nBinSize:1
@AM	binSizeList: [5000]
@AM	binSize:5000	nBin:0
Traceback (most recent call last):
  File "h5py/_proxy.pyx", line 316, in h5py._proxy.needs_bkg_buffer
KeyError: 'Conversion function not found (no appropriate function for conversion path)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/bin/snaptools", line 38, in <module>
    parse_args()    
  File "/anaconda3/lib/python3.7/site-packages/snaptools/parser.py", line 168, in parse_args
    verbose=args.verbose)
  File "/anaconda3/lib/python3.7/site-packages/snaptools/add_bmat.py", line 175, in snap_bmat
    f.create_dataset("AM/"+str(bin_size)+"/binChrom",data=[np.string_(key[0]) for key in bin_dict_list[bin_size]], dtype=h5py.special_dtype(vlen=bytes), compression="gzip", compression_opts=9);
  File "/anaconda3/lib/python3.7/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/anaconda3/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 170, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 221, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 152, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 318, in h5py._proxy.needs_bkg_buffer
TypeError: Operation not defined for data type class (operation not defined for data type class)

**Comment by r3fang** [comment]
it’s python version issue. I don’t have time to test it on >python3.6. If you can use python2.7, it should be fine

--
Rongxin Fang
Ph.D. Student, Ren Lab
Ludwig Institute for Cancer Research
University of California, San Diego
