### ISSUE TITLE
dex-fastq permission error

### ISSUE THREAD

**Issue by mvinyard** [r3fang/SnapATAC#91]
I am attempting to run `dex-fastq` on some cellranger-atac mkfastq outputs. For simplicity's sake, I executed the following command in the same directory where my fastq files are stored (for a single library). I have pasted the output error message below. I am looking into whether this is an issue on my end or not, but I was hoping to get your feedback since I am more or less running it as advertised without any modifications.

```
$ snaptools dex-fastq --input-fastq=MM2384_S2_L001_R1_001.fastq.gz --output-fastq=MM2384_S2_L001_R1_001.dex.fastq.gz --index-fastq-list MM2384_S2_L001_R2_001.fastq.gz
```
Here is my output error message:
```
Traceback (most recent call last):
  File "/home/mvinyard/anaconda3/bin/snaptools", line 38, in <module>
    parse_args()    
  File "/home/mvinyard/anaconda3/lib/python3.7/site-packages/snaptools/parser.py", line 78, in parse_args
    index_fastq_list=args.index_fastq_list
  File "/home/mvinyard/anaconda3/lib/python3.7/site-packages/snaptools/dex_fastq.py", line 89, in dex_fastq
    fout = gzip.open(output_fastq, 'wb')
  File "/home/mvinyard/anaconda3/lib/python3.7/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/home/mvinyard/anaconda3/lib/python3.7/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
PermissionError: [Errno 13] Permission denied: 'MM2384_S2_L001_R1_001.dex.fastq.gz'
```

**Comment by r3fang** [comment]
Hi Micheal,

It’s python version issue. Snaptools does not work on python 3.7. If you can use 2.7, the problem should be gone. 

Also, for 10X data, we recommend to run cell ranger for preprocessing and use the tsv file to generate the snap file. This is because cell ranger will correct the barcode error based on a white list which snaptools does not.  

Let me know if you need more help!

**Comment by mvinyard** [comment]
Thank you!

**Comment by mvinyard** [comment]
Hi again, so I created a new env, installing python 2.7 and reinstalled snaptools along with its dependencies. I ran the exact same command as above and received the following, similar error message. 
```
Traceback (most recent call last):
  File "/home/mvinyard/anaconda3/envs/SnapATAC/bin/snaptools", line 38, in <module>
    parse_args()    
  File "/home/mvinyard/anaconda3/envs/SnapATAC/lib/python2.7/site-packages/snaptools/parser.py", line 78, in parse_args
    index_fastq_list=args.index_fastq_list
  File "/home/mvinyard/anaconda3/envs/SnapATAC/lib/python2.7/site-packages/snaptools/dex_fastq.py", line 89, in dex_fastq
    fout = gzip.open(output_fastq, 'wb')
  File "/home/mvinyard/anaconda3/envs/SnapATAC/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/home/mvinyard/anaconda3/envs/SnapATAC/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 13] Permission denied: 'MM2384_S2_L001_R1_001.dex.fastq.gz'
```
If you have any further insights, I would greatly appreciate it! 
Best,
Michael

**Comment by r3fang** [comment]
Hi Micheal,

It seems the error was caused by writing permission issue. It is likely because you do not have the permission to create the resulting file in the current folder. To test it, can you try to create a file by “touch tmp.txt” in the current fold and see if you get any error?

--
Rongxin Fang
Ph.D. Student, Ren Lab
Ludwig Institute for Cancer Research
University of California, San Diego

**Comment by mvinyard** [comment]
Thanks @r3fang I figured this out
